import * as React from 'react';
import { Dialog as D, Select as S, DropdownMenu as M, Checkbox as C, Tabs as T } from 'radix-ui';
import { Check, ChevronDown, X } from 'lucide-react';
import { Button } from './button';
export const Input=(props:React.ComponentProps<'input'>)=><input {...props} className={'input '+(props.className||'')}/>;
export const Textarea=(props:React.ComponentProps<'textarea'>)=><textarea {...props} className={'input textarea '+(props.className||'')}/>;
export function Select({value,onChange,options,label,disabled=false}:{value:string;onChange:(v:string)=>void;options:[string,string][];label:string;disabled?:boolean}){return <S.Root value={value} onValueChange={onChange} disabled={disabled}><S.Trigger className="select-trigger" aria-label={label}><S.Value placeholder="Choose…"/><S.Icon><ChevronDown size={14}/></S.Icon></S.Trigger><S.Portal><S.Content className="select-content" position="popper" sideOffset={5}><S.Viewport>{options.map(([key,title])=><S.Item className="select-item" key={key} value={key}><S.ItemText>{title}</S.ItemText><S.ItemIndicator><Check size={14}/></S.ItemIndicator></S.Item>)}</S.Viewport></S.Content></S.Portal></S.Root>}
export function Checkbox({checked,onChange,label}:{checked:boolean;onChange:(v:boolean)=>void;label:string}){const id=React.useId();return <label className="check-label" htmlFor={id}><C.Root id={id} className="checkbox" checked={checked} onCheckedChange={v=>onChange(v===true)}><C.Indicator><Check size={13}/></C.Indicator></C.Root>{label}</label>}
export function Modal({title,description,children,open,onClose,drawer=false}:{title:string;description?:string;children:React.ReactNode;open:boolean;onClose:()=>void;drawer?:boolean}){return <D.Root open={open} onOpenChange={v=>!v&&onClose()}><D.Portal><D.Overlay className="overlay"/><D.Content className={drawer?'modal drawer':'modal'} aria-describedby={description?'dialog-description':undefined}><header className="modal-header"><div><D.Title>{title}</D.Title>{description&&<D.Description id="dialog-description">{description}</D.Description>}</div><D.Close asChild><Button variant="ghost" size="icon" aria-label="Close"><X size={18}/></Button></D.Close></header><div className="modal-body">{children}</div></D.Content></D.Portal></D.Root>}
export function Menu({trigger,items}:{trigger:React.ReactNode;items:{label:string;action:()=>void;danger?:boolean}[]}){return <M.Root><M.Trigger asChild>{trigger}</M.Trigger><M.Portal><M.Content className="menu-content" align="end" sideOffset={5}>{items.map(item=><M.Item key={item.label} className={'menu-item '+(item.danger?'danger':'')} onSelect={item.action}>{item.label}</M.Item>)}</M.Content></M.Portal></M.Root>}
export function Tabs({value,onChange,items}:{value:string;onChange:(v:string)=>void;items:[string,React.ReactNode][]}){return <T.Root value={value} onValueChange={onChange}><T.List className="tabs">{items.map(([key,name])=><T.Trigger key={key} value={key}>{name}</T.Trigger>)}</T.List></T.Root>}
export function Field({label,help,children}:{label:string;help?:string;children:React.ReactNode}){return <div className="field"><div className="field-label">{label}</div>{help&&<p className="muted">{help}</p>}{children}</div>}
export function Empty({title,children}:{title:string;children?:React.ReactNode}){return <div className="empty"><h3>{title}</h3>{children}</div>}
