import {useEffect,useState,type ReactNode} from 'react';
import {useQuery} from '@tanstack/react-query';
import {Plus,FolderKanban,Activity,PlugZap,Settings,Menu,RefreshCw,CheckCircle2,AlertTriangle,Clock3,FolderPlus} from 'lucide-react';
import {api,queryClient,type Bootstrap,type Project,type Harness,label,attention} from './lib/api';
import {Button} from './components/ui/button';
import {Modal,Field,Input,Textarea,Select,Checkbox,Empty} from './components/ui/controls';
import Board from './components/Board';
import TaskWorkspace from './components/TaskWorkspace';
type Page='board'|'activity'|'connections'|'settings';

export default function App(){
 const {data,error,isLoading,refetch}=useQuery({queryKey:['bootstrap'],queryFn:()=>api<Bootstrap>('/api/bootstrap')});
 const [page,setPage]=useState<Page>('board'),[projectId,setProjectId]=useState<number>(),[taskId,setTaskId]=useState<number>(),[newTask,setNewTask]=useState(false),[toast,setToast]=useState(''),[mobileOpen,setMobileOpen]=useState(false);
 const project=data?.projects.find(item=>item.id===(projectId??data?.projects[0]?.id));
 useEffect(()=>{if(!projectId&&data?.projects[0])setProjectId(data.projects[0].id)},[data,projectId]);
 const notify=(message:string)=>{setToast(message);window.setTimeout(()=>setToast(''),3000)};
 const refresh=()=>{queryClient.invalidateQueries({queryKey:['bootstrap']});refetch()};
 if(isLoading)return <div className="app-loading"><Brand markOnly/>Opening Aludra…</div>;
 if(error||!data)return <div className="app-loading"><AlertTriangle/><p>{(error as Error)?.message||'Unable to load Aludra.'}</p><Button onClick={()=>refetch()}>Try again</Button></div>;
 if(taskId&&project)return <TaskWorkspace project={project} taskId={taskId} onBack={()=>setTaskId(undefined)} refresh={refresh} notify={notify}/>;
 const subtitle:Record<Page,string>={board:'Task board',activity:'Activity',connections:'Connections',settings:'Project settings'};
 return <div className="app-shell">
  <aside className="rail">
   <Brand/>
   <nav><span className="rail-label">Workspace</span><Nav icon={<FolderKanban/>} label="Tasks" active={page==='board'} onClick={()=>setPage('board')}/><Nav icon={<Activity/>} label="Activity" active={page==='activity'} onClick={()=>setPage('activity')}/></nav>
   <div className="rail-projects"><span className="rail-label">Projects</span>{data.projects.map(item=><button key={item.id} className={item.id===project?.id?'project-select active':'project-select'} onClick={()=>{setProjectId(item.id);setPage('board')}}><span>{item.name}</span><small>{item.tasks.length}</small></button>)}</div>
   <nav className="setup-nav"><span className="rail-label">Setup</span><Nav icon={<PlugZap/>} label="Connections" active={page==='connections'} onClick={()=>setPage('connections')}/><Nav icon={<Settings/>} label="Settings" active={page==='settings'} onClick={()=>setPage('settings')}/></nav>
   <div className="rail-footer"><b>Workspace ready</b><span>Coder connected · {data.harnesses.length} harnesses</span></div>
  </aside>
  <div className="mobile-top"><Brand/><Button variant="ghost" size="icon" aria-label="Menu"><Menu/></Button></div>
  <button className="mobile-menu-button" aria-label="Menu" onClick={()=>setMobileOpen(true)}><Menu size={22}/></button>
  {mobileOpen&&<div className="mobile-drawer"><button className="mobile-drawer-close" aria-label="Close menu" onClick={()=>setMobileOpen(false)}>×</button><Brand/><nav><span className="rail-label">Workspace</span><Nav icon={<FolderKanban/>} label="Tasks" active={page==='board'} onClick={()=>{setPage('board');setMobileOpen(false)}}/><Nav icon={<Activity/>} label="Activity" active={page==='activity'} onClick={()=>{setPage('activity');setMobileOpen(false)}}/></nav><div className="rail-projects"><span className="rail-label">Projects</span>{data.projects.map(item=><button key={item.id} className={item.id===project?.id?'project-select active':'project-select'} onClick={()=>{setProjectId(item.id);setPage('board');setMobileOpen(false)}}><span>{item.name}</span><small>{item.tasks.length}</small></button>)}</div><nav><span className="rail-label">Setup</span><Nav icon={<PlugZap/>} label="Connections" active={page==='connections'} onClick={()=>{setPage('connections');setMobileOpen(false)}}/><Nav icon={<Settings/>} label="Settings" active={page==='settings'} onClick={()=>{setPage('settings');setMobileOpen(false)}}/></nav></div>}
  <main className="main">
   <header className="bar"><div className="crumb"><b>{project?.name||'Workspace'}</b><span>{subtitle[page]}</span></div><div className="actions"><Button variant="secondary" onClick={()=>setPage('settings')}>Project settings</Button><Button onClick={()=>setNewTask(true)}><Plus size={15}/>New task</Button></div></header>
   <section className="page">{page==='board'&&project&&<Board project={project} onOpen={setTaskId} onNew={()=>setNewTask(true)} refresh={refresh} notify={notify}/>} {page==='activity'&&<ActivityPage projects={data.projects} onOpen={setTaskId}/>} {page==='connections'&&<Connections data={data} refresh={refresh} notify={notify}/>} {page==='settings'&&<SettingsPage project={project} harnesses={data.harnesses} refresh={refresh} notify={notify}/>}</section>
  </main>
  <NewTask open={newTask} project={project} onClose={()=>setNewTask(false)} onCreated={id=>{setNewTask(false);refresh();setTaskId(id)}} notify={notify}/>
  {toast&&<div role="status" className="toast">{toast}</div>}
 </div>;
}
function Brand({markOnly=false}:{markOnly?:boolean}){return <div className={markOnly?'brand-mark':'brand'}><svg viewBox="0 0 190 125" aria-hidden="true"><path d="M18 106 L64 29 Q75 10 87 29 L136 106 L112 106 L76 49 L42 106 Z" fill="#5367FF"/><path d="M154 27 C154 38 160 44 171 44 C160 44 154 50 154 61 C154 50 148 44 137 44 C148 44 154 38 154 27 Z" fill="#F3C969"/></svg>{!markOnly&&<span>Aludra</span>}</div>}
function Nav({icon,label,active,onClick}:{icon:ReactNode;label:string;active:boolean;onClick:()=>void}){return <button className={'nav-item '+(active?'active':'')} onClick={onClick}>{icon}<span>{label}</span></button>}
function NewTask({open,project,onClose,onCreated,notify}:{open:boolean;project?:Project;onClose:()=>void;onCreated:(id:number)=>void;notify:(s:string)=>void}){
 const [text,setText]=useState(''),[start,setStart]=useState(false),[permission,setPermission]=useState('inherit');
 async function create(){if(!project)return;try{const result=await api<{id:number}>(`/api/projects/${project.id}/tasks`,'POST',{text,start,tool_permissions:permission});onCreated(result.id)}catch(error){notify((error as Error).message)}}
 return <Modal open={open} onClose={onClose} title="New task" description="Start with the outcome. Change inherited defaults only when this work needs an exception."><Field label="What should be done?"><Textarea autoFocus value={text} onChange={event=>setText(event.target.value)} placeholder="Describe the outcome and acceptance criteria…"/></Field><Field label="Task permission mode"><Select label="Task permission mode" value={permission} onChange={setPermission} options={[[`inherit`,`Use project default`],[`ask`,`Ask before every tool`],[`standard`,`Standard harness permissions`],[`auto`,`Allow the harness to proceed`]]}/></Field><Checkbox label="Start the harness immediately" checked={start} onChange={setStart}/><p className="inherited"><b>Inherited setup</b><br/>Harness order, failover policy, environment, and verification come from <em>{project?.name||'this project'}</em>.</p><div className="actions"><Button variant="secondary" onClick={onClose}>Cancel</Button><Button disabled={!text.trim()||!project} onClick={create}>Create task</Button></div></Modal>;
}
function ActivityPage({projects,onOpen}:{projects:Project[];onOpen:(id:number)=>void}){const tasks=projects.flatMap(project=>project.tasks.map(task=>({...task,project:project.name}))).sort((a,b)=>b.id-a.id);return <><div className="pagehead"><div><p className="eyebrow">Workspace</p><h1>Activity</h1><p className="muted">Task events, ordered by when they happened.</p></div></div><div className="activity">{tasks.map(task=><button key={task.id} className="event" onClick={()=>onOpen(task.id)}><time className="time">Recently</time><span className={'eventmark '+(attention(task)?'attention':'')}>{attention(task)?<AlertTriangle/>:task.run?.status==='complete'?<CheckCircle2/>:<Clock3/>}</span><span><b>{task.text}</b><p>{task.run?.message||'Task created'} · {task.project}</p></span></button>)}{!tasks.length&&<Empty title="No activity yet"/>}</div></>}
function Connections({data,refresh,notify}:{data:Bootstrap;refresh:()=>void;notify:(s:string)=>void}){return <><div className="pagehead"><div><p className="eyebrow">Readiness</p><h1>Connections</h1><p className="muted">A connection is ready only when access, availability, and environment are all ready.</p></div></div><div className="grid2">{data.harnesses.map(harness=><article className="connection" key={harness.key}><div className="connectiontop"><span className={'connectionlogo '+harness.key}>{harness.label.slice(0,2)}</span><b>{harness.label}</b><span className={'badge '+(harness.availability?.code==='ready'?'':'warn')}>{harness.availability?.label||'Unknown'}</span></div><p>{harness.availability?.reason||'Availability has not been checked.'}</p><Button variant="secondary" size="sm" onClick={async()=>{try{await api('/api/scan','POST',{});refresh();notify('Harness availability refreshed')}catch(error){notify((error as Error).message)}}}>Refresh status</Button></article>)}</div></>}
function SettingsPage({project,harnesses,refresh,notify}:{project?:Project;harnesses:Harness[];refresh:()=>void;notify:(s:string)=>void}){
 const [scope,setScope]=useState('global'),[category,setCategory]=useState('execution'),[name,setName]=useState(project?.name||''),[verify,setVerify]=useState(project?.verify_command||''),[mode,setMode]=useState(project?.default_mode||'supervised'),[failover,setFailover]=useState(Boolean(project?.auto_failover));
 useEffect(()=>{setName(project?.name||'');setVerify(project?.verify_command||'');setMode(project?.default_mode||'supervised');setFailover(Boolean(project?.auto_failover))},[project]);
 if(!project)return <Empty title="Choose a project first"/>;
 const currentProjectId=project.id;
 async function save(){try{await api(`/api/projects/${currentProjectId}`,'POST',{name,verify_command:verify,default_mode:mode,auto_failover:failover?1:0});refresh();notify('Project settings saved')}catch(error){notify((error as Error).message)}}
 return <><div className="pagehead"><div><p className="eyebrow">{project.name}</p><h1>Settings</h1><p className="muted">Choose a scope first. Every value shows where it comes from.</p></div></div><div className="settingslayout"><nav className="settingsnav"><button className={category==='execution'?'on':''} onClick={()=>setCategory('execution')}>Execution</button><button className={category==='sessions'?'on':''} onClick={()=>setCategory('sessions')}>Sessions</button><button className={category==='review'?'on':''} onClick={()=>setCategory('review')}>Review & delivery</button></nav><div className="settingbody"><div className="scope"><button className={scope==='global'?'on':''} onClick={()=>setScope('global')}>Global</button><button className={scope==='project'?'on':''} onClick={()=>setScope('project')}>Project</button><button className={scope==='task'?'on':''} onClick={()=>setScope('task')}>Task override</button></div>{scope==='global'?<SettingRow title="Harness order" source="Global default" description="Eligible harnesses are considered in this order."><ol className="harness-order">{harnesses.map(harness=><li key={harness.key}><span className="connectionlogo">{harness.label[0]}</span>{harness.label}<span>{harness.enabled&&harness.installed?'Eligible':'Unavailable'}</span></li>)}</ol></SettingRow>:scope==='project'?<><SettingRow title="Project name" source="Project value"><Input value={name} onChange={event=>setName(event.target.value)}/></SettingRow><SettingRow title="Verification command" source="Project value"><Input value={verify} onChange={event=>setVerify(event.target.value)}/></SettingRow><SettingRow title="Run mode" source="Project value"><Select label="Run mode" value={mode} onChange={setMode} options={[[`supervised`,`Ask before starting and finishing`],[`unattended`,`Run and finish automatically`]]}/></SettingRow><SettingRow title="Failover policy" source="Project value"><Checkbox label="Continue automatically with the next eligible harness" checked={failover} onChange={setFailover}/></SettingRow><div className="settings-save"><Button onClick={save}>Save project settings</Button></div></>:<Empty title="Task overrides live with each task"><p>Open a task and use Task settings to override environment, mode, and session budget.</p></Empty>}</div></div></>;
}
function SettingRow({title,source,description,children}:{title:string;source:string;description?:string;children:ReactNode}){return <section className="settingrow"><div><b>{title}</b>{description&&<p>{description}</p>}<span className="source">{source}</span></div><div>{children}</div></section>}
