import React from 'react';
import ReactDOM from 'react-dom/client';
import { QueryClientProvider } from '@tanstack/react-query';
import { queryClient } from './lib/api';
import App from './App';
import './styles.css';
import './layout-fixes.css';
import './memories.css';
import './mobile-board.css';
import './task-design.css';
import './reference-rail.css';
import './task-header.css';
import './approved-task.css';
import './approved-focus.css';
import './approved-mobile.css';
import './approved-saved-views.css';
import './approved-delivery.css';
import './approved-modal.css';
import './approved-cta.css';
import './approved-board-geometry.css';
import './brand-marks.css';
import './harness-models.css';
import './attachments.css';
ReactDOM.createRoot(document.getElementById('root')!).render(<React.StrictMode><QueryClientProvider client={queryClient}><App/></QueryClientProvider></React.StrictMode>);
